name: mss_planning_poker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable: ^6.1.5
  get_it: ^7.2.0
  either_dart: ^0.1.4
  injectable: ^1.5.3
  firebase_core: ^1.13.1
  json_annotation: ^4.4.0
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  cloud_firestore_odm: ^1.0.0-dev.10
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  flex_color_scheme: ^4.2.0
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  cloud_firestore_odm_generator: ^1.0.0-dev.10
  injectable_generator: ^1.5.2
  freezed: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
